-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Helper Functions
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 1. DROP EXISTING TABLES (Caution: This will delete existing data)
DROP TABLE IF EXISTS public.user_dashboard CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public."Appointment" CASCADE;
DROP TABLE IF EXISTS public.services CASCADE;
DROP TABLE IF EXISTS public.sessions CASCADE;
DROP TABLE IF EXISTS public.review CASCADE;
DROP TABLE IF EXISTS public.hospitals CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public."Config" CASCADE;

-- 2. Create Tables

-- Table: profiles
CREATE TABLE public.profiles (
  full_name text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  user_id uuid not null,
  constraint profiles_pkey primary key (user_id),
  constraint profiles_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

-- Table: Appointment
CREATE TABLE public."Appointment" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "firstName" text null,
  "lastName" text null,
  email text null,
  phone text null,
  "dateOfBirth" date null,
  gender text null,
  "appointmentType" text null,
  "consultationMethod" text null,
  "medicalCenter" text null,
  "preferredDate" date null,
  "preferredTime" text null,
  reason text null,
  symptoms text null,
  "isNewPatient" text null,
  "currentMedications" text null,
  allergies text null,
  "medicalHistory" text null,
  "paymentId" text null,
  user_id uuid not null,
  meeting_link text null,
  meet_link text null,
  "orderId" text null,
  constraint appointment_pkey primary key (id),
  constraint appointment_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- Table: Config
CREATE TABLE public."Config" (
  key text not null,
  value jsonb null,
  updated_at timestamp with time zone null default now(),
  constraint Config_pkey primary key (key)
) TABLESPACE pg_default;

-- Table: hospitals
CREATE TABLE public.hospitals (
  id bigint not null,
  created_at timestamp with time zone not null default now(),
  name character varying null,
  address character varying null,
  phone character varying null,
  "doctorSchedule" jsonb null,
  constraint hospitals_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: review
CREATE TABLE public.review (
  id bigint generated by default as identity not null,
  review text null,
  created_at timestamp with time zone not null default now(),
  name text null,
  constraint review_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: services
CREATE TABLE public.services (
  id uuid not null default gen_random_uuid (),
  title text not null default ''::text,
  description text null default ''::text,
  features jsonb null default '[]'::jsonb,
  duration text null default ''::text,
  price jsonb null default '{}'::jsonb,
  icon text null,
  "appointmentType" text null default ''::text,
  constraint services_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: sessions
CREATE TABLE public.sessions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  title text null,
  duration integer null,
  date date null,
  time time without time zone null,
  meet_link text null,
  constraint sessions_pkey primary key (id),
  constraint sessions_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- Table: settings
CREATE TABLE public.settings (
  id bigint not null,
  created_at timestamp with time zone not null default now(),
  booking_range integer null default 30,
  online_slots jsonb null,
  session_quota jsonb null,
  session_slots jsonb null default '{}'::jsonb,
  constraint settings_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: user_dashboard
CREATE TABLE public.user_dashboard (
  user_id uuid not null,
  "firstName" text null,
  "lastName" text null,
  email text null,
  phone numeric null,
  "dateOfBirth" date null,
  gender text null,
  allergies text null,
  "medicalHistory" text null,
  appointments text null,
  sessions text null,
  message text null,
  prescribe text null,
  appointment_id bigint null,
  meet_link text null,
  "orderId" text null,
  "paymentId" text null,
  constraint user_dashboard_pkey primary key (user_id),
  constraint user_dashboard_appointment_id_fkey foreign KEY (appointment_id) references "Appointment" (id) on delete set null,
  constraint user_dashboard_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

-- 3. Indexes

CREATE UNIQUE INDEX unique_online_appointment_slot on public."Appointment" using btree (
  "preferredDate",
  "preferredTime",
  "consultationMethod"
) TABLESPACE pg_default
where
  ("consultationMethod" = 'online'::text);

CREATE UNIQUE INDEX unique_offline_appointment_slot on public."Appointment" using btree (
  "preferredDate",
  "preferredTime",
  "consultationMethod",
  "medicalCenter"
) TABLESPACE pg_default
where
  ("consultationMethod" = 'offline'::text);

-- 4. Trigger Functions

-- Sync Appointment to Dashboard Function
CREATE OR REPLACE FUNCTION public.sync_appointment_to_dashboard()
RETURNS trigger AS $$
BEGIN
  UPDATE public.user_dashboard
  SET 
    "firstName" = new."firstName",
    "lastName" = new."lastName",
    phone = CASE WHEN new.phone ~ '^[0-9]+$' THEN new.phone::numeric ELSE NULL END,
    "dateOfBirth" = new."dateOfBirth",
    gender = new.gender,
    allergies = new.allergies,
    "medicalHistory" = new."medicalHistory",
    appointment_id = new.id,
    meet_link = COALESCE(new.meet_link, new.meeting_link),
    "orderId" = new."orderId",
    "paymentId" = new."paymentId"
  WHERE user_id = new.user_id;
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Triggers

-- Trigger on Appointment
DROP TRIGGER IF EXISTS on_appointment_created_sync ON public."Appointment";
CREATE TRIGGER on_appointment_created_sync
  AFTER INSERT OR UPDATE ON public."Appointment"
  FOR EACH ROW EXECUTE FUNCTION public.sync_appointment_to_dashboard();

-- Trigger on Profiles
DROP TRIGGER IF EXISTS profiles_set_updated_at ON public.profiles;
CREATE TRIGGER profiles_set_updated_at 
  BEFORE UPDATE ON public.profiles 
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 6. Seed Data (Dietitian Theme)
INSERT INTO public.services (title, description, features, duration, price, icon, "appointmentType") VALUES
('Diet Consultation', 'Personalized diet plan and health assessment.', '["BMI Check", "Custom Diet Plan", "Weekly Follow-up"]', '30 min', '{"inr": {"min": 500, "max": 500}, "min": 500, "max": 500}'::jsonb, 'Apple', 'diet_consult'),
('Weight Management', 'Specialized program for weight loss or gain.', '["Calorie Tracking", "Exercise Guidelines", "Progress Monitoring"]', '45 min', '{"inr": {"min": 800, "max": 800}, "min": 800, "max": 800}'::jsonb, 'Scale', 'weight_mgmt'),
('Diabetes Diet Plan', 'Dietary management for diabetes control.', '["Sugar Level Monitoring", "Low GI Diet Plan", "Doctor Coordination"]', '45 min', '{"inr": {"min": 700, "max": 700}, "min": 700, "max": 700}'::jsonb, 'Activity', 'diabetes'),
('Sports Nutrition', 'Performance boosting nutrition for athletes.', '["Protein Calculation", "Pre/Post Workout Meals", "Supplement Guide"]', '45 min', '{"inr": {"min": 1000, "max": 1000}, "min": 1000, "max": 1000}'::jsonb, 'Dumbbell', 'sports'),
('Pediatric Nutrition', 'Healthy eating plans for growing children.', '["Growth Chart Analysis", "Picky Eater Solutions", "Nutrient Dense Meals"]', '30 min', '{"inr": {"min": 600, "max": 600}, "min": 600, "max": 600}'::jsonb, 'Baby', 'pediatric');

-- 7. Initial Settings
INSERT INTO public.settings (id, booking_range, online_slots) VALUES
(1, 30, '["09:00 AM", "10:00 AM", "11:00 AM", "02:00 PM", "03:00 PM", "04:00 PM"]');
