-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id)
);

-- Table: Appointment
CREATE TABLE IF NOT EXISTS public."Appointment" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  "firstName" text,
  "lastName" text,
  email text,
  phone text,
  "dateOfBirth" text,
  gender text,
  "appointmentType" text,
  "consultationMethod" text,
  "medicalCenter" text,
  "preferredDate" text,
  "preferredTime" text,
  reason text,
  symptoms text,
  "isNewPatient" boolean DEFAULT false,
  "currentMedications" text,
  allergies text,
  "medicalHistory" text,
  status text DEFAULT 'pending',
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  meet_link text,
  "orderId" text,
  "paymentId" text
);

-- Table: user_dashboard
CREATE TABLE IF NOT EXISTS public.user_dashboard (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  "firstName" text,
  "lastName" text,
  phone numeric, 
  "dateOfBirth" text,
  gender text,
  allergies text,
  "medicalHistory" text,
  appointment_id bigint REFERENCES public."Appointment"(id) ON DELETE SET NULL,
  meet_link text,
  "orderId" text,
  "paymentId" text
);

-- Table: services
CREATE TABLE IF NOT EXISTS public.services (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  title text NOT NULL,
  description text,
  features jsonb, -- Array of strings
  duration text,
  price numeric DEFAULT 500, -- Default price if not specified
  icon text,
  "appointmentType" text,
  created_at timestamptz DEFAULT now()
);

-- Seed Services for Dietitian Theme
INSERT INTO public.services (title, description, features, duration, price, icon, "appointmentType") VALUES
('Diet Consultation', 'Personalized diet plan and health assessment.', '["BMI Check", "Custom Diet Plan", "Weekly Follow-up"]', '30 min', 500, 'Apple', 'diet_consult'),
('Weight Management', 'Specialized program for weight loss or gain.', '["Calorie Tracking", "Exercise Guidelines", "Progress Monitoring"]', '45 min', 800, 'Scale', 'weight_mgmt'),
('Diabetes Diet Plan', 'Dietary management for diabetes control.', '["Sugar Level Monitoring", "Low GI Diet Plan", "Doctor Coordination"]', '45 min', 700, 'Activity', 'diabetes'),
('Sports Nutrition', 'Performance boosting nutrition for athletes.', '["Protein Calculation", "Pre/Post Workout Meals", "Supplement Guide"]', '45 min', 1000, 'Dumbbell', 'sports'),
('Pediatric Nutrition', 'Healthy eating plans for growing children.', '["Growth Chart Analysis", "Picky Eater Solutions", "Nutrient Dense Meals"]', '30 min', 600, 'Baby', 'pediatric');

-- Functions and Triggers

-- 1. Handle New User
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (user_id, full_name)
  VALUES (new.id, new.raw_user_meta_data->>'full_name');

  INSERT INTO public.user_dashboard (user_id, email)
  VALUES (new.id, new.email);

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 2. Sync Appointment
CREATE OR REPLACE FUNCTION public.sync_appointment_to_dashboard()
RETURNS trigger AS $$
BEGIN
  UPDATE public.user_dashboard
  SET 
    "firstName" = new."firstName",
    "lastName" = new."lastName",
    -- Cast phone safely only if it looks numeric, else leave null or handle appropriately
    phone = CASE WHEN new.phone ~ '^[0-9]+$' THEN new.phone::numeric ELSE NULL END,
    "dateOfBirth" = new."dateOfBirth",
    gender = new.gender,
    allergies = new.allergies,
    "medicalHistory" = new."medicalHistory",
    appointment_id = new.id,
    meet_link = new.meet_link,
    "orderId" = new."orderId",
    "paymentId" = new."paymentId"
  WHERE user_id = new.user_id;
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_appointment_created_sync ON public."Appointment";
CREATE TRIGGER on_appointment_created_sync
  AFTER INSERT OR UPDATE ON public."Appointment"
  FOR EACH ROW EXECUTE FUNCTION public.sync_appointment_to_dashboard();
